SELECT SUM(g.SCORE) SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL 
FROM HR_DEPARTMENT d
JOIN HR_EMPLOYEES e ON d.DEPT_ID= e.DEPT_ID
JOIN HR_GRADE g ON e.EMP_NO = g.EMP_NO
WHERE g.YEAR = 2022
GROUP BY g.EMP_NO
ORDER BY SCORE DESC
LIMIT 1